services:
  postgres:
    networks:
      - pg-network
    image: postgres:latest
    environment:
      POSTGRES_USER: alt_school_user
      POSTGRES_PASSWORD: secretPassw0rd
      POSTGRES_DB: alt_school_db
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    networks:
      - pg-network
    image: dpage/pgadmin4:8.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80" 
volumes:
  postgres_data:
networks:
  pg-network:
